version: '3'

services:
  neo4j:
    image:  neo4j:3.0
    ports:
     - 7474:7474
     - 7687:7687
    container_name:  neo4j
    network_mode:  host
    volumes:
     - '$HOME/neo4j/data:/data'

  friends-book:
    image:  friends-book
    build:  ../friends-book
    restart:  always
    network_mode:  host
    container_name:  friends-book
    depends_on:
      - neo4j
    ports:
      - 8080:8080
    expose:
      - 8080
